= Solar Panel Behavior
:xrefstyle: short
ifdef::env-handout[]
:!toc:
endif::[]
:reproducible:

include::subs.adoc[]


:fillin: pass:[<span style="display:inline-block; width:8em; border-bottom:1px solid;"></span>]



== Lamp info

[horizontal]
Lamp name / type:: {fillin} {nbsp}incandescent | LED

Rated input power:: {fillin} {W}

Rated brightness:: {fillin} {nbsp}lm

---

[horizontal]
Measured input power:: {fillin} {W}


== Solar panel info

[horizontal]
Num. cells in series:: {fillin}

Open circuit voltage:: {fillin} {V}

&rarr; computed:: {fillin} {V} / cell




== Shading cells

The series connection of the individual solar cells into the complete panel has consequences for how partial shade affects the panel's output.


[horizontal]
Measure *short-circuit current*:: {fillin} {mA}


---

* [ ] Block panel slowly from one direction while watching the measured current.

{blank} +


* [ ] Block panel slowly from 90&deg; to the last direction, watching the measured current.

{blank} +




<<<
== Current vs. Angle


The short-circuit current represents the power generated by a solar panel (multiplied by the "`loaded`" voltage gives power in watts).
The optimum voltage decreases a bit when the temperature of the solar cell increases.

[.right]
image::current-vs-angle.svg[width=400]



* [ ] Mark the measured short-circuit current value for 0&deg; tilt angle and *decide your _y_-axis scale marks*.

* [ ] Tilt the panel up to about 15&deg; and mark on the plot the new short-circuit current.
Estimate the angle by moving it to 45&deg; and then splitting into thirds.

* [ ] Continue to tilt the panel to each angle and record the current.





